echo -n '( '
echo -n '["clear-day"]="5 9" '
echo -n '["clear-night"]="5 10" '
echo -n '["cloudy"]="3 11" '
echo -n '["fog"]="3 11" '
echo -n '["partly-cloudy-day"]="4 11" '
echo -n '["partly-cloudy-night"]="4 11" '
echo -n '["rain"]="5 9" '
echo -n '["sleet"]="5 9" '
echo -n '["snow"]="5 9" '
echo -n ' )'
